# Generated by Django 5.2.6 on 2025-09-28 11:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(max_length=255)),
                ('org_name', models.CharField(max_length=255)),
                ('exam_date', models.DateField()),
                ('sheet_template', models.CharField(choices=[('AS-01', 'AS-01'), ('AS-02', 'AS-02'), ('AS-03', 'AS-03'), ('AS-04', 'AS-04')], default='AS-01', max_length=10)),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('pass_mark', models.IntegerField(blank=True, null=True)),
                ('exam_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UploadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('filetype', models.CharField(max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='UploadedFile',
        ),
    ]
