# Generated by Django 5.2.6 on 2025-09-30 08:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omr', '0004_exam_share_uuid_exam_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='share_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
