# Generated by Django 5.2.6 on 2025-09-30 08:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omr', '0005_alter_exam_share_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='share_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
