# Generated by Django 5.2.6 on 2025-09-30 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('omr', '0006_alter_exam_share_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='share_uuid',
        ),
    ]
